### ISSUE TITLE
Market Place

### ISSUE THREAD

**Issue by bhargavi539** [RailsGirlsCPH/mentor-mentee-platform#103]
As a Mentor, I want to reach the mentees who need my suggestions. So I can write a post about my skills and give my contact details which can be viewed globally for everyone.So that the mentee can reach the mentee directly. Or If the user knows a person who is need of the help. The user should be able to share the post to the particular user

**Comment by diwanow** [comment]
Duplicate of #105 

Feel free to re-open elaborating more if you feel this is not truly a duplicate.
