### ISSUE TITLE
Add setup instructions to the project Readme

### ISSUE THREAD

**Issue by nlshopova** [RailsGirlsCPH/mentor-mentee-platform#11]
Fill in https://github.com/RailsGirlsCPH/mentor-mentee-platform/blob/master/mentor-mentee-platform/README.md

Important: Add instructions on how to run the project locally

**Comment by nynnejc** [comment]
I want to propose that we change the text in the README file to better explain the project to people who come across our project. I'd like to see:

- short introduction to the project and story of who is building it

- how to contribute

- code of conduct

- documentation

**Comment by sibsmc** [comment]
I have added more information to the README.md file located in the server folder. 
The information I added focuses only on how to set up the project on the users local machine. 
If changes are accepted I propose closing issue  #23, leaving #11 open as more documentation is required. Perhaps we could link to the README.md in the server folder?
