### ISSUE TITLE
Consistent use of quotes 

### ISSUE THREAD

**Issue by sibsmc** [RailsGirlsCPH/mentor-mentee-platform#155]
Simple Task - all quotes should be of type '', note ""

**Comment by dennis** [comment]
Rubocop can be nice to enforce these kind of things (might require some configuration to avoid being too annoying)

**Comment by sibsmc** [comment]
Issue has been completed, added style guide in README.md and changed existing quotes in server directory. Have not implemented Rubocop yet as it may add to confusion when merging at this stage.
