### ISSUE TITLE
Validate new user data: password

### ISSUE THREAD

**Issue by sibsmc** [RailsGirlsCPH/mentor-mentee-platform#197]
Validate new user data: 

Password is not visible in plain text (user doesn't see the characters they type)

**Comment by gargshruti30** [comment]
Hey @sibsmc, I and @AnjaliGarg13 are interested in working on this issue.

**Comment by sibsmc** [comment]
Hi @AnjaliGarg13 and @gargshruti30 
That sounds great, no authentication has been implemented yet so the passwords in the database are just placeholders. But there are 3 open issues to set up and trial an authentication solution.  #32 #33 and #34 
Are you interested in setting it up in the backend, or setting up the front end for each solution?
Either way let me know if you would like to meet up to discuss.

**Comment by gargshruti30** [comment]
@sibsmc 
Hey. We went through the 3 issues you mentioned and were not able to figure out what are the needs of this particular issue. Yes, we would like to meet you to discuss the issue further. Could you tell me the details about the next meetup?
