### ISSUE TITLE
Start/learn Vue

### ISSUE THREAD

**Issue by krem13** [RailsGirlsCPH/mentor-mentee-platform#20]
Read documentation.
Maybe try to start it on your computer.

**Comment by nynnejc** [comment]
What tools/resources are you using for this? I want to follow along!

**Comment by zoeyzou** [comment]
> What tools/resources are you using for this? I want to follow along!

Hey Nynne, we are mainly reading the documentation of Vue, on the official website they also link to a lot of learning resources.
