### ISSUE TITLE
Document that 2.6.2 is the Ruby version used by the Rails app

### ISSUE THREAD

**Issue by olleolleolle** [RailsGirlsCPH/mentor-mentee-platform#23]
The README could have a note and a link to a version manager explanation - "we use Ruby 2.6.2, here's how to also use that".

**Comment by nirmalathapa** [comment]
There is a ticket to fill in the README documentation open issue  #11. But I can definitely write a small note mentioning where to get the ruby version

**Comment by lujeanpierre** [comment]
Issue dealt with https://github.com/RailsGirlsCPH/mentor-mentee-platform/pull/45
