### ISSUE TITLE
Bundler warning: Your Gemfile lists the gem pry-rescue (>= 0) more than once

### ISSUE THREAD

**Issue by olleolleolle** [RailsGirlsCPH/mentor-mentee-platform#233]
**Describe the bug**

Travis (yay) reports this on install:

```
Your Gemfile lists the gem pry-rescue (>= 0) more than once.

You should probably keep only one of them.
```

And, Bundler's tip is a good one!

**To Reproduce**
1. Go to https://travis-ci.com/RailsGirlsCPH/mentor-mentee-platform/builds/149191698#L191
2. Observe the warning

Or:

1. `bundle install` 
2. Observe the warning

**Expected behavior**

No warning output.

**Comment by sibsmc** [comment]
Duplicate pry-rescue has now been removed.
