### ISSUE TITLE
i tried running app frontend this is what i get after succesfull compilation.

### ISSUE THREAD

**Issue by developer22-university** [RailsGirlsCPH/mentor-mentee-platform#267]
![Screenshot (124)_LI](https://user-images.githubusercontent.com/51835554/77684622-3b72ba80-6fc0-11ea-8621-f98061f1c214.jpg)

just want to verify is this correct page where i have landed after following the instructions, any suggestion to see remaining contents of the frontend of the app

**Comment by developer22-university** [comment]
any suggestion  how to run build command afterwards

**Comment by archanaserver** [comment]
Hey @developer22-university 
Yes, you have landed on the correct page. And that's the only thing present in the front end of this website. For the any contribution we contributor have to start it from scratch. They have made this beginner-friendly.
