### ISSUE TITLE
Containerized development setup

### ISSUE THREAD

**Issue by diwanow** [RailsGirlsCPH/mentor-mentee-platform#299]
**Summary**
Development setup and installing the tools necessary is often the first (and possibly detrimental) obstacle for people who would like to contribute. Throughout development tools also evolve so setup needs to be refreshed. Finally, issues with tool and version clashes when developing on a physical machine are relatively common.
For that sake, we can introduce containerized development setup that can reduce the number of tools to be installed initially. In addition this would allow unified experience for contributors + can help drive common practices and tooling.

**Reasoning**
Such a setup should help anyone to start developing quicker since

- local machine setup will not be needed e.g. no need to install ruby or other tools and potentially struggle with them
- the setup will be the same for everyone so cases of "it works on my machine" should be fewer/eliminated
- it should be more starter friendly (hopefully) - no matter seniority, dealing with installation, configuration and things that for some reason don't work is always annoying and frustrating

**Suggestions & notes**

- Regarding IDE support to make things better (i.e. click a button and you don't need to know all stuff I mentioned above, it just works), at least in VS Code there is support via an extension (and this can be configured for everyone via a VS code workspace).  I've seen jetbrains' IDEs and Visual Studio also support containerized development + starting from command line should also be possible - it would be a matter of documenting the options or picking 1 to ease maintenance.
- Regarding OS, especially on Linux machines the setup should probably work out of the box; Windows might require something more (Docker for Windows or WSL, maybe) - making the setup work across both OS types might be one of the challenges.

**Links**
- [Remote development with VS Code](https://verschaffelt.be/2019/06/24/remote-development-with-visual-studio-code/)
- [Detailed explanation for using rails debug](https://share.atelie.software/using-visual-studio-code-to-debug-a-rails-application-running-inside-a-docker-container-3416918d8cc8)
- [More on debugging + other VS Code configuration](https://github.com/Microsoft/vscode-recipes/tree/master/debugging-Ruby-on-Rails#bonus)
- [Ruby on Rails on Windows Subsystem for Linux (WSL2)](https://www.hanselman.com/blog/RubyOnRailsOnWindowsIsNotJustPossibleItsFabulousUsingWSL2AndVSCode.aspx)

**Comment by sibsmc** [comment]
Will close this issue as we have docker set up for react, rails and postgres
