### ISSUE TITLE
Spike: Research how to add Swagger to the Rails API

### ISSUE THREAD

**Issue by nlshopova** [RailsGirlsCPH/mentor-mentee-platform#41]
Use swagger to document the API 
More info: https://swagger.io/

**Acceptance criteria**

1. Make a plan how to implement
2. Create issues 
3. Document in the Wiki

**Comment by olleolleolle** [comment]
:wave: Big fan of Swagger, here.

[`rswag`](https://github.com/domaindrivendev/rswag) is an extension to [`rspec-rails`](https://relishapp.com/rspec/rspec-rails/docs), which allows you to annotate your _integration tests_ with Swagger information.
