### ISSUE TITLE
Setup build validation for pull requests 

### ISSUE THREAD

**Issue by nlshopova** [RailsGirlsCPH/mentor-mentee-platform#42]
Suggestions for pipeline: 
Azure DevOps 
Travis CI 
Shippable

**Acceptance criteria:**

1. Make sure a build is triggered when a pull request is created/updated 
2. Run unit tests
3. Don't allow merging a pull request if the build validation fails

**Comment by sibsmc** [comment]
Repository linked to Travis-CI.

**Comment by sibsmc** [comment]
pull request #232  handled adding travis-ci to pull request for server branch. Travis shell script can be used by the front end in the future
