### ISSUE TITLE
Make Rails app with front page

### ISSUE THREAD

**Issue by diwanow** [RailsGirlsCPH/mentor-mentee-platform#7]
**Acceptance criteria**
There is a bare bones Rails app with default set up/home page

**Comment by nirmalathapa** [comment]
Hi! I would like to setup the rails app and display simple welcome message. Let me know if anyone wants to work on this :)

**Comment by nynnejc** [comment]
Me me me!

**Comment by mikker** [comment]
Be aware that Rails 6 is juuuuust around the corner (beta 2 right now) and it includes Webpack as a default asset bundler. Just so you don't struggle too long with setting up the old Sprockets 😃 

To get the most recent pre-release of Rails, run
```sh
gem install rails --pre
# verify we're using the correct version when initializing
rails -v # should output Rails 6.0.0.beta2
```

**Comment by nirmalathapa** [comment]
I used Rails 5.1.6.1 to set up the app

**Comment by nirmalathapa** [comment]
@nynnejc I just created a pull request and I have added the welcome message with simple dummy button Also i used little older version of both ruby and rails is there going to be a problem later?

**Comment by mikker** [comment]
Happy to help with upgrading the Rails version if you need it. 5.1 is from November so not necessarily ancient. I just thought since this is a brand new project there's no reason _not_ to use the latest and greatest.

@nirmalathapa What a lovely illustration in your PR 👏 looks good!
