### ISSUE TITLE
Add validation information to registration form

### ISSUE THREAD

**Issue by diwanow** [RailsGirlsCPH/mentor-mentee-platform#9]
As a potential user
I can see whether my registration was successful
So that I can either try again or log in

**Acceptance criteria**

- If registration fails i.e. username is not unique for the system, the registration form must have an error message "Username must be unique"

Depends on #8 to be done first

**Comment by sibsmc** [comment]
'email' and 'username' are defined as unique attributes in table api_user, uniqueness is validated in model spec and error message is returned if non-unique information entered when creating user.
